server:
  port: 8000

spring:
  application:
    name: spring-webflux-guide
  webflux:
    base-path: /api
  data:
    mongodb:
      host: mongo
      port: 27017
      database: mydatabase
      username: admin
      password: adminpassword

  kafka:
    consumer:
      group-id: group-idd
      auto-offset-reset: earliest
      bootstrap-servers: localhost:9092

logging:
  level:
    io:
      reflectoring: DEBUG
    org:
      springframework:
        web: INFO
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG
    reactor:
      netty:
        http:
          client: DEBUG